### ISSUE TITLE
Can't find some default apps on Catalina

### ISSUE THREAD

**Issue by Gluestick** [oNaiPs/dmenu-mac#10]
A lot of the default apps on Catalina (e.g. System Preferences, Activity Monitor, Music) are unfindable. Other default installed apps (e.g. Garage Band) can be found. It seems all the apps that can be found, are listed in `ls /Applications/`, but some of the default applications seem to have some special status and can't even be found with `ls /Applications/`.

I've been using dmenu-mac for a few years on Mojave and older without issues, but only just stumbled upon this on my new Macbook with Catalina installed.

### Workaround
This can be worked around by creating an alias in Finder with `Cmd + Ctrl + A`, and making sure it ends with `.app`. The alias can then be found by dmenu-mac, and you can launch the application that way.

**Comment by oNaiPs** [comment]
@Gluestick thanks for the report!

Will update to Catalina soon and will try to fix.

**Comment by frayment** [comment]
@Gluestick I have fixed this in my commit.

@oNaiPs I don't mean to rush you - I was having the same issue and thought I would fix it myself. I have thus created a pull request. 😃

**Comment by oNaiPs** [comment]
Thanks @frayment! @Gluestick can you confirm if the fixed worked so I can close this issue?

**Comment by frayment** [comment]
@oNaiPs Thankyou, and confirmed working! Happy new years. :)

**Comment by Gluestick** [comment]
Works great, thanks @frayment!
