### ISSUE TITLE
Application quits after fufilling querying or pressing 't'.

### ISSUE THREAD

**Issue by tomlister** [oNaiPs/dmenu-mac#13]
Dmenu seems to quit after fufilling a querying or pressing 't'.
I have to reopen dmenu to perform another query.
I'm on Catalina btw.
Running binary in terminal and pressing 't' outputs this.
`tom.lister@MacBook-Air MacOS % ./dmenu-mac 
Fatal error: Can't form a Character from an empty String
zsh: illegal hardware instruction  ./dmenu-mac`

**Comment by tomlister** [comment]
It appears that FuzzySearch.swift cannot handle the Ü in Ubersicht and crashes.
Renaming Übersicht.app to Ubersicht.app fixed the problem but is not a permament solution.

**Comment by oNaiPs** [comment]
Fixed in the 0.5.0 release.
