### ISSUE TITLE
Mojave version

### ISSUE THREAD

**Issue by marco-silva0000** [oNaiPs/dmenu-mac#14]
hello, I would really like to try it, but my mac is managed my the company and it doesn't support 10.5 yet, could you target a build for 10.4, or make a readme file with the build steps?

**Comment by oNaiPs** [comment]
@marco-silva0000 you should be able to build the project using xcode without any special step.

**Comment by marco-silva0000** [comment]
this better be a good app... 
I had to create an apple id, then add a payment method, then add an address, then the app store didn't work because of some unknown reason, so I left it and tried a day latter, now I could login to the app store but I still cant download xcode because the store only has the latest version, so I had to explore apple's developer website til I found the version I guess is compatible, 11.3.1, and now I'm waiting 7 hours for the download to complete...
rant over, I'll try to build tomorrow...

**Comment by marco-silva0000** [comment]
success! if you build an app with a target of 10.14, it wont run on 10.15? If not, then you should build it with the latest compatible target possible, I had to do 0 code changes and it was fine.

**Comment by oNaiPs** [comment]
@marco-silva0000 that's great to hear! Perhaps you can add a PR with the change.

**Comment by Di9** [comment]
@oNaiPs you wrote `*Mac OS X 10.8 or greater required.` but actually your app is required only 10.15... So sad that you don't care about all variety of mac os users.

**Comment by Snazzyham** [comment]
@marco-silva0000 do you think you could make a PR for that? I don't really wanna upgrade to catalina but would love to try this out.

**Comment by marco-silva0000** [comment]
@Snazzyham I've pushed it to my fork just now, but it has some additional changes, I'll make a better commit for only this later

**Comment by Snazzyham** [comment]
@marco-silva0000 dope, I'd check it out but seems like I still need to download xcode to build. Downloading xcode now, wanna see if I can add reading from a `.dmenurc` file to source apps or bash scripts from different directories but I have no experience with swift at all lmao.

**Comment by augustebaum** [comment]
Any updates on this? The readme says one needs OSX 10.8 or later; I have 10.14 but when I try to open the app it tells me I need 10.15.

**Comment by augustebaum** [comment]
Follow-up: I'm on OSX 10.14.6 and managed to get this to work by building from source using Xcode 11.3.1.
Steps I followed:
1. Open the `xcodeproj` file in Xcode
2. Go to the build settings, see screenshot
3. Change the "macOS Deployment Target" to 10.14
4. Build
5. Find the `.app` file (had to use `fd` -- I'm not used to Xcode)

**Comment by acagastya** [comment]
@augustebaum Could you please make it available on brew?  Maybe `dmenu-mac-mojave`?  That would be greatly appreciated!

**Comment by augustebaum** [comment]
I'm not familiar with the packaging process in Homebrew and I don't know where to host the files. @acagastya If you're up for it, perhaps I can send you the files and let you deal with it?

**Comment by oNaiPs** [comment]
Hi All,

I just made a new release that makes the minimum version 10.13. Let me know if it works for you.

Download from this repo, or just wait for the update to be available through brew (https://github.com/Homebrew/homebrew-cask/pull/108028)

Thanks!

**Comment by acagastya** [comment]
Thank you @oNaiPs, greatly appreciate it!

**Comment by molleweide** [comment]
Awesome!! I’m also gonna try it now 😃

**Comment by oNaiPs** [comment]
Closing as done
