### ISSUE TITLE
Shortcuts doesn't work

### ISSUE THREAD

**Issue by capitanBOBO** [oNaiPs/dmenu-mac#19]
Default shortcut and remaped shortcut doesn't work. Maybe I should make some configuration before?

**Comment by GameAudioImplementation** [comment]
seems to work only immediately after running the binary. the process still shows as running but shortcuts don't work after a period of time.

**Comment by TheOmegaCarrot** [comment]
I am also experiencing this issue on MacOS 10.15.7.

**Comment by KevinApodaca** [comment]
Following up on this, still can't use the shortcut (cmd + shift + enter, or any variation for that matter) to work with this app. 

macOS 11.3.1 on m1 mac mini
install via `brew install --cask dmenu-mac` but same issue with manual download from the releases page

even disabled spotlight search, still no luck. I have to open the app manually either by spotlight or by clicking it. 

Is there some other thing that needs to be configured before getting keyboard shortcut to work ?

**Comment by oNaiPs** [comment]
Hi all can you try with latest 0.7.0 if you still have this problem?

**Comment by oNaiPs** [comment]
Closing issue. Please reopen if still happens on latest
