### ISSUE TITLE
Add favourites/bookmarks

### ISSUE THREAD

**Issue by drewauff** [oNaiPs/dmenu-mac#20]
Really needs to save frequently used apps function, its a giant pain-in-the-ass to have to scroll though the list time after time for a often used app rather then dmenu "completing" in the entry with the most used.

Some more options would be nice ie. transparency, font type and sizes (perhaps even color).

**Comment by McFrappe** [comment]
May i ask if you type the app that you want to open? 

The purpose of using "dmenu" is to simply have a launcher that you use to search for a given application and launch it. 

I cannot see how this would be incorporated into dmenu, that is my opinion though. By all means if the developers finds it useful then sure.

**Comment by drewauff** [comment]
Oh, for example, if I enter Mail to open mail.app I get everything that has the word mail except the actual mail.app

**Comment by McFrappe** [comment]
So, you mean that when you type `mail`, you dont get the `.app` as the first option? Or an option at all?
![Screenshot 2021-07-16 at 5 27 33 PM](https://user-images.githubusercontent.com/17787601/125971967-a0dc45f4-bbde-46f2-877f-be0fb76c53ae.png)

**Comment by drewauff** [comment]
Yes that is correct..

Also, can you add feature where I can open System Preferance Panes.

**Comment by McFrappe** [comment]
Have you checked where your mail app is located?

**Comment by drewauff** [comment]
works now after latest update. Thanks.
