### ISSUE TITLE
Release 0.7.0 does not work as expected

### ISSUE THREAD

**Issue by McFrappe** [oNaiPs/dmenu-mac#22]
It seems that when running the 0.7.0 build, it does not show any results.
See image below for reference

<img width="1680" alt="Screenshot 2021-07-19 at 1 05 57 PM" src="https://user-images.githubusercontent.com/17787601/126151010-d41def17-c336-4a89-b4c7-d7429e816d92.png">
<img width="1680" alt="Screenshot 2021-07-19 at 1 06 05 PM" src="https://user-images.githubusercontent.com/17787601/126151015-df2e4e8a-977c-4688-ae55-cff1f084d674.png">
<img width="1680" alt="Screenshot 2021-07-19 at 1 06 12 PM" src="https://user-images.githubusercontent.com/17787601/126151018-d74609f0-39bb-4950-bdac-9c51b7848952.png">

**Comment by oNaiPs** [comment]
Fixed in 305bdcd. Look out for 0.7.1
