### ISSUE TITLE
Apple Silicon

### ISSUE THREAD

**Issue by martinbaillie** [oNaiPs/dmenu-mac#25]
Great project! `dmenu` is all I've ever really wanted from a fuzzy application finder on macOS.

Would it be possible to produce aarch64/Apple Silicon releases?

**Comment by oNaiPs** [comment]
aarch64 support will be available on next release (see https://github.com/oNaiPs/dmenu-mac/commit/5ff4ffc0f6e8d180f9c06529fa195585365afb58). Thanks!
