### ISSUE TITLE
dmenu-mac is killed instantly

### ISSUE THREAD

**Issue by jose** [oNaiPs/dmenu-mac#28]
Hi,

I've just installed dmenu-mac (v0.7.2) with [brew](https://brew.sh/), as suggested, but it does not seem to be working on my box (macOS Big Sur v11.5.2, intel cpu) as it is killed instantly
```
$ dmenu-mac
[1]    54962 killed     dmenu-mac
```

Is there any flag I could use to get some debug information? Am I missing anything here?

Best, Jose

**Comment by oNaiPs** [comment]
@jose thanks for trying it out (awesome nickname btw) could you check if there's any logs on Console.app?

**Comment by jose** [comment]
I didn't manage to find anything useful on Console.app.  However, I noticed that macOS was complaining about `dmenu-mac` not being a unknown app while looking at 'System Preferences' -> 'Security & Privacy' -> 'General' -> 'Allow apps downloaded from:'.  Once I pressed 'Allow to open' (or something similar, can't remember) it started working as expected.

Thanks.
