### ISSUE TITLE
custom entries via pipe

### ISSUE THREAD

**Issue by languitar** [oNaiPs/dmenu-mac#3]
Would be nice if there was a way to provide custom entries instead of applications so that I can used this for [pass](https://www.passwordstore.org/) as a front-end for auto typing passwords.

**Comment by oNaiPs** [comment]
That's a great idea! I feel that the project is a bit too early to be able to implement such a thing, but what would be the use case you envision? Why via pipe?

**Comment by languitar** [comment]
This is the interface dmenu provides. I would use it to pipe my password manager entries in there, where some other script may determine what appropriate entries are.

**Comment by rien333** [comment]
There is an couple of other really interesting other use cases for this too, for example jumping between windows by their name. Or maybe see this [video](https://www.youtube.com/watch?v=R9m723tAurA).

**Comment by kdb424** [comment]
I am working on, ironically enough, new password software (designed to replace pass) that is going to integrate with dmenu, and happen to run OSX on my dev machine. I would love to see this available as well to get it running on more OS's. Would gladly test, but am not familiar with C code, so can't contribute code.

**Comment by oNaiPs** [comment]
I just implemented this! Any folks willing to test?

Example usage:
```
echo No Yes | <dmenu-mac.app_location>/Contents/MacOS/dmenu-mac
```

Test build: https://github.com/oNaiPs/dmenu-mac/suites/3148223591/artifacts/72367962

**Comment by 0xConnorRhodes** [comment]
Firstly, thank you so much for this project! I'm a Linux user who uses a Mac at work, and a dmenu alternative for MacOS will allow me to transfer much of my workflow.

I've tested the build, and I found a problem. This test build works only when the options are separated by spaces.

This works:
```bash
echo "No Yes" | <dmenu-mac.app_location>/Contents/MacOS/dmenu-mac
```
dmenu-mac displays two choices "No" and "Yes" and prints the chosen option to standard out.

This does not work as expected:
```bash
echo "No\nYes" |  <dmenu-mac.app_location>/Contents/MacOS/dmenu-mac
```
dmenu-mac displays only one multi-line choice. This means that you cannot use dmenu-mac to filter through multi-line output.

As far as I can tell, the way other fuzzy-finding programs (dmenu, fzf, rofi) decide which character to use as a string separator is:
1. Use newline `\n` if it is present.
2. If no newline character is present, use space.

To make dmenu-mac work for this use-case, you could implement this behavior and/or you could provide a command-line flag to allow the user to specify their own delimiter.

**Comment by oNaiPs** [comment]
@0xConnorRhodes thanks for looking into this! How does the Linux version work with spaces and quotes?

**Comment by oNaiPs** [comment]
I’ll do the changes you propose!

**Comment by 0xConnorRhodes** [comment]
> @0xConnorRhodes thanks for looking into this! How does the Linux version work with spaces and quotes?

For spaces and quotes, dmenu interprets the entire string inside the quotes as one option.

Actually I did some testing on Linux, and (by default) dmenu only splits at newline characters. `echo yes no | dmenu` produces only one option `yes no`. 

So the default behavior is that dmenu interprets `echo yes no | dmenu` and `echo "yes no" | dmenu` both as one option `yes no`. You would need to explicitly override the delimiter character to get different behavior.

**Comment by oNaiPs** [comment]
Closing this issue as done in 0.7.0 release. See README for more instructions. Please create a new one for enhancements.
