### ISSUE TITLE
Render issue / yabai compatibility

### ISSUE THREAD

**Issue by fiskhest** [oNaiPs/dmenu-mac#9]
I'm using [yabai](https://github.com/koekeishiya/yabai) and the integrated status bar that comes bundled with it. 

I'm trying to add dmenu-mac to my setup but it does not offset with regards to yabai's status bar height, and the dmenu panel is rendered behind the status bar:
<img width="1437" alt="Skärmavbild 2019-08-06 kl  12 54 42" src="https://user-images.githubusercontent.com/26885267/62534410-6057c900-b849-11e9-9ad2-dd5f626ce379.png">

Is it possible to configure dmenu-mac and specify an offset or margin/padding, or any other way to force it to render above the status bar?

**Comment by oNaiPs** [comment]
@fiskhest there's no way to do this right now. Perhaps you could contribute?

**Comment by fiskhest** [comment]
Wish I could but I have no knowledge of swift nor the time to learn. Thanks for clarifying.

**Comment by oNaiPs** [comment]
@fiskhest is this still applicable?

**Comment by fiskhest** [comment]
According to https://github.com/koekeishiya/yabai/issues/486 the built in status bar has been removed and from my very limited comparison the alternatives seem more customizable.
